# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='fase',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horas',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
    ]
