# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20180104_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaPos',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grade.Disciplina')),
                ('posX', models.PositiveIntegerField()),
                ('posY', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='requisitos',
            field=models.ManyToManyField(blank=True, to='grade.Disciplina'),
        ),
    ]
