# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_auto_20180107_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinapos',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grade.Disciplina'),
        ),
    ]
