# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_auto_20180107_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinapos',
            name='posX',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disciplinapos',
            name='posY',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
