# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_auto_20180107_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaView',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grade.Disciplina')),
                ('posX', models.PositiveIntegerField(default=0)),
                ('posY', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#000000', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='disciplinapos',
            name='id',
        ),
        migrations.DeleteModel(
            name='DisciplinaPos',
        ),
    ]
